language: scala
jdk:
  - oraclejdk8
  - oraclejdk7
scala:
  - 2.11.4
  - 2.10.4
secure:
  "HFoy5/NdvRoZvm/tlxwezhxs2eQb+/qZ2TriOppbBgbZs1QETt4uxrCeslyz88M3+WItPwFKmlHxMoWW4J7ibJ/O78zVHJ2lNq2adFy3wYDMdEvxnJjGvKRyPtnCuCplFHvn/s+U37bsMwtf3F4olWcSYg/BrXoTBB+A7trGGmc="
after_success:
  ./publish-documentation.sh